name: Deploy Images to EC2
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nrmnqdds
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/nrmnqdds/imaluum-v2:latest
          cache-from: type=registry,ref=ghcr.io/nrmnqdds/imaluum-v2:cache
          cache-to: type=registry,mode=max,ref=ghcr.io/nrmnqdds/imaluum-v2:cache,image-manifest=true

  deploy:
    needs: push-store-image
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login ghcr.io -u nrmnqdds -p ${{ secrets.GHCR_TOKEN }}
            docker compose pull
            docker compose up --force-recreate --build -d webapp
            docker system prune -a -f
